[project]
name = "acp-beeai-workshop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "acp-sdk>=0.9.1",
    "beeai-framework>=0.1.21",
]
